version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/ssl:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: unless-stopped

  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "./mariadb/conf/:/mnt/"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PASSWORD}
      WP_DATABASE_NAME: "wordpress"
      WP_DATABASE_USR:  ${MYSQL_USER}
      WP_DATABASE_PWD:  ${MYSQL_PASSWORD}

  wordpress:
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - wp-volume:/var/www/
    container_name: wordpress

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/Шаблоны/Docker/wordpress
