version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/http.d/
      - ./nginx/tools:/etc/nginx/ssl/
      - wp_volume:/var/www/
    restart: unless-stopped

  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "./mariadb/conf/:/mnt/"
    restart: unless-stopped

  wordpress:
    build:
      context: .
      dockerfile: wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - wp_volume:/var/www/
    container_name: wordpress

volumes:
  wp_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/wordpress