#!/bin/sh
rc-service mariadb start 2> /dev/null
mysql -u mysql -e "CREATE DATABASE ${WP_DATABASE_NAME};"
mysql -u mysql -e \
"CREATE USER '${WP_DATABASE_USR}'@'%' IDENTIFIED BY '${WP_DATABASE_PWD}';
GRANT ALL PRIVILEGES ON ${WP_DATABASE_NAME}.* TO '${WP_DATABASE_USR}'@'%' IDENTIFIED BY '${WP_DATABASE_PWD}';
GRANT ALL PRIVILEGES ON ${WP_DATABASE_NAME}.* TO '${WP_DATABASE_USR}'@'localhost' IDENTIFIED BY '${WP_DATABASE_PWD}';
ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PWD}';
FLUSH PRIVILEGES;"
/usr/bin/mysqld
